# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
#              "you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, "
#              "you are entitled to a state funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]

question_data = {"response_code": 0,
                 "results": [
                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                      "question": "Greenland is almost as big as Africa.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Entertainment: Film", "type": "boolean",
                      "difficulty": "easy",
                      "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Politics", "type": "boolean", "difficulty": "easy",
                      "question": "Denmark has a monarch.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Entertainment: Board Games", "type": "boolean",
                      "difficulty": "easy",
                      "question": "The Angry Video Game Nerd&#039;s alter ego is &quot;Board James&quot;.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Mythology", "type": "boolean", "difficulty": "easy",
                      "question": "According to Greek Mythology, Atlas was an Olympian God.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Entertainment: Video Games", "type": "boolean",
                      "difficulty": "easy",
                      "question": "Valve&#039;s &quot;Portal&quot; and &quot;Half-Life&quot; franchises exist within the same in-game universe.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Animals", "type": "boolean", "difficulty": "easy",
                      "question": "The Killer Whale is considered a type of dolphin.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Science & Nature", "type": "boolean",
                      "difficulty": "easy",
                      "question": "An average human can go two weeks without water.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Entertainment: Film", "type": "boolean",
                      "difficulty": "easy",
                      "question": "&quot;Foodfight!&quot; earned less than $80,000 at box office.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Science: Mathematics", "type": "boolean",
                      "difficulty": "easy",
                      "question": "An equilateral triangle always has every angle measuring 60&deg;.",
                      "correct_answer": "True", "incorrect_answers": ["False"]}
                 ]
                 }
